name: Cache build binaries
description: Cache or restore if necessary

runs:
  using: composite
  steps:
    - name: Cache build
      uses: actions/cache@v3
      id: cache-build
      env:
        cache-name: build
        key-1: ${{ hashFiles('yarn.lock') }}
        key-2: ${{ hashFiles('apps/**/**.[jt]s', 'apps/**/**.[jt]sx', 'packages/**/**.[jt]s', 'packages/**/**.[jt]sx', '!**/node_modules') }}
        key-3: ${{ github.event.pull_request.number || github.ref }}
        key-4: ${{ github.sha }}
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          ${{ github.workspace }}/apps/prerender/.next
          **/.turbo/**
          **/dist/**
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ env.key-3 }}-${{ env.key-4 }}

    - run: yarn build
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: bash
