version: "3.8"

x-defaults-build: &defaults-build
  context: ../
  dockerfile: ./docker/Dockerfile

x-defaults-healthcheck: &defaults-healthcheck
  start_period: 5s
  interval: 5s
  timeout: 5s
  retries: 5

services:
  worker-live:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/live
    ports:
      - 8096:8096
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/live/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8096/' ]
  worker-staff-picks:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/staff-picks
    ports:
      - 8095:8095
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/staff-picks/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8095/' ]
  worker-nft:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/nft
    ports:
      - 8094:8094
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/nft/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8094/' ]
  worker-groups:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/groups
    ports:
      - 8093:8093
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/groups/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8093/' ]
  worker-preferences:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/preferences
    ports:
      - 8092:8092
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/preferences/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8092/' ]
  worker-feeds:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/feeds
    ports:
      - 8091:8091
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/feeds/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8091/' ]
  worker-invite:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/invite
    ports:
      - 8090:8090
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/invite/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8090/' ]
  worker-achievements:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/achievements
    ports:
      - 8089:8089
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/achievements/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8089/' ]
  worker-leafwatch:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/leafwatch
    ports:
      - 8088:8088
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/leafwatch/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8088/' ]
  worker-oembed:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/oembed
    ports:
      - 8087:8087
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/oembed/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8087/' ]
  worker-ens:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/ens
    ports:
      - 8086:8086
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/ens/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8086/' ]
  worker-snapshot-relay:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/snapshot-relay
    ports:
      - 8085:8085
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/snapshot-relay/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8085/' ]
  worker-freshdesk:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/freshdesk
    ports:
      - 8084:8084
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/freshdesk/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8084/' ]
  worker-metadata:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/metadata
    ports:
      - 8083:8083
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/metadata/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8083/' ]
  worker-sts:
    build:
      <<: *defaults-build
      args:
        - WORKSPACE=@workers/sts
    ports:
      - 8082:8082
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/packages/workers/sts/node_modules
    healthcheck:
      <<: *defaults-healthcheck
      test: [ 'CMD', 'curl', '-f', '-k', 'http://localhost:8082/' ]
