version: "3.8"

services:
  prerender:
    extends:
      file: docker-compose.apps.yml
      service: prerender
  web:
    extends:
      file: docker-compose.apps.yml
      service: web
  workers:
    extends:
      file: docker-compose.all-workers.yml
      service: workers
