name: CI

on:
  pull_request_target:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: Type check
    uses: ./.github/workflows/typecheck.yml

  lint:
    name: Lint check
    uses: ./.github/workflows/lint.yml

  prettier:
    name: Prettier check
    uses: ./.github/workflows/prettier.yml

  build:
    name: Build
    needs: [typecheck, lint, prettier]
    uses: ./.github/workflows/build.yml

  test:
      name: Test
      needs: [build]
      uses: ./.github/workflows/test.yml
  