name: CI

on:
  pull_request_target:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml

  typecheck:
    name: Typecheck
    needs: [prepare]
    uses: ./.github/workflows/typecheck.yml

  lint:
    name: Lint
    needs: [prepare]
    uses: ./.github/workflows/lint.yml

  prettier:
    name: Prettier
    needs: [prepare]
    uses: ./.github/workflows/prettier.yml

  build:
    name: Build
    needs: [typecheck, lint, prettier]
    uses: ./.github/workflows/build.yml

  test:
      name: Test
      needs: [build]
      uses: ./.github/workflows/test.yml

  required:
    needs: [typecheck, lint, prettier, build, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
