name: CI

on:
  pull_request_target:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type check
    uses: ./.github/workflows/type.yml

  lint-check:
    name: Lint check
    uses: ./.github/workflows/lint.yml

  prettier-check:
    name: Prettier check
    uses: ./.github/workflows/prettier.yml

      # - name: Build 🎁
      #   run: yarn build

      # - name: Run Tests 🧪
      #   run: yarn test:e2e
