name: Deploy Web Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Set up QEMU 🐳
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: heyxyz/web:latest

      - name: Trigger Web deployment 🚀
        uses: appleboy/ssh-action@master
        env:
          NEXT_PUBLIC_OG_URL: ${{ secrets.NEXT_PUBLIC_OG_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: NEXT_PUBLIC_OG_URL
          script: deployctl web