name: Deploy API Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Set up QEMU 🐳
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API-mainnet image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          build-args: |
            NEXT_PUBLIC_LENS_NETWORK=mainnet
          push: true
          tags: heyxyz/api-mainnet:latest

      - name: Build and push API-testnet image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          build-args: |
            NEXT_PUBLIC_LENS_NETWORK=testnet
          push: true
          tags: heyxyz/api-testnet:latest

      - name: Build and push API-staging image 🚀
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          build-args: |
            NEXT_PUBLIC_LENS_NETWORK=staging
          push: true
          tags: heyxyz/api-staging:latest

      - name: Trigger API Deployment 🚀
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL_MAINNET: ${{ secrets.DATABASE_URL_MAINNET }}
          DATABASE_URL_TESTNET: ${{ secrets.DATABASE_URL_TESTNET }}
          DATABASE_URL_STAGING: ${{ secrets.DATABASE_URL_STAGING }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          SECRET: ${{ secrets.SECRET }}
          EVER_ACCESS_KEY: ${{ secrets.EVER_ACCESS_KEY }}
          EVER_ACCESS_SECRET: ${{ secrets.EVER_ACCESS_SECRET }}
          LENS_IPFS_AUTH_KEY: ${{ secrets.LENS_IPFS_AUTH_KEY }}
          IPAPI_KEY: ${{ secrets.IPAPI_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          IRYS_PRIVATE_KEY: ${{ secrets.IRYS_PRIVATE_KEY }}
          IMAGEKIT_URL: ${{ secrets.IMAGEKIT_URL }}
          ZENDESK_API_KEY: ${{ secrets.ZENDESK_API_KEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DATABASE_URL_MAINNET,DATABASE_URL_TESTNET,DATABASE_URL_STAGING,CLICKHOUSE_PASSWORD,SECRET,EVER_ACCESS_KEY,EVER_ACCESS_SECRET,LENS_IPFS_AUTH_KEY,IPAPI_KEY,GOOGLE_API_KEY,IRYS_PRIVATE_KEY,IMAGEKIT_URL,ZENDESK_API_KEY
          script: deployctl api