name: Deploy cloudflare workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v3

      - name: Setup node 🍀
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install 📦
        run: pnpm run install --frozen-lockfile

      - name: Deploy 🚀
        run: |
          pnpm add wrangler -g
          pnpm run workers:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
