name: Prettier check

on:
  workflow_call:

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-install
      - run: yarn prettier
