name: Test

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/cache-build
      - run: yarn test:e2e
